[datasets.qanta]
name = "QANTA Dataset"
paper = "Quizbowl: The Case for Incremental Question Answering"
type = "Factoid Question Answering"
bib = ""
description = "Qanta is a factoid question answering dataset based on Quizbowl."
slug = "qanta"

[datasets.curiosity]
name = "Curiosity Dataset"
paper = "Information Seeking in the Spirit of Learning: a Dataset for Conversational Curiosity"
type = "Dialog"
bib = """\
@inproceedings{rodriguez2020curiosity,
    title = {Information Seeking in the Spirit of Learning: a Dataset for Conversational Curiosity},
    author = {Pedro Rodriguez and Paul Crook and Seungwhan Moon and Zhiguang Wang},
    year = 2020,
    booktitle = {Empirical Methods in Natural Language Processing}
}"""
description = "The Curiosity dataset is an information-seeking dialog dataset."
slug = "curiosity"